### ISSUE TITLE
ROX 6.0 CAD support

### ISSUE THREAD

**Issue by druchaty** [ciofeca/sdsdata#1]
Hello Alfonso,

I would like to know is it possible to read all the training data from Sigma ROX 6.0 CAD. Is there any datasheet for this?

Additionally, if I understand correctly, Sigma Data Center allows to draw graphs using trip information. Is it possible to implement in the future?

Thanks,
Nikolay

**Comment by ciofeca** [comment]
Sorry, they seem totally different products: BC16.xx units only store a few counters, while ROX units log way more data. As far as I know, Sigma does not publish its own datasheets; you'll need to reverse-engineer the protocol used by the official SigmaDataCenter software.
